v1.0.1 : Bug-fix

diff --git a/ipns-link b/ipns-link
--- a/ipns-link
+++ b/ipns-link
@@ -3,7 +3,7 @@ export LANGUAGE=C LANG=C LC_ALL=C
 export PATH="${HOME}"/.bin:"${PATH}"
 # Remark: All public-facing functions/subcmds are prefixed with _ipns_link_ and is not exported
 
-export version=1.0.0
+export version=1.0.1
 export republish_interval=900 #seconds
 export root_repo="${HOME}/.ipns-link"
 export origin_repo="${root_repo}/origin-server"
@@ -27,6 +27,16 @@ _ipns_link_about(){
   "
 } >&2 2>/dev/null
 
+kill_proc_tree(){
+  # Brief: Kill (with SIGKILL) all descendants of the process id given, with the given signal, if any
+  # Usage: kill_proc_tree <pid> [<SIG>] # Default SIG=KILL
+  local pid
+  for pid in $(pgrep -P "${1}"); do
+    kill_proc_tree "${pid}" "${2}" &
+  done
+  kill -CONT "${1}"; kill -"${2:-KILL}" "${1}"
+} &>/dev/null; export -f kill_proc_tree
+
 log(){
   # Brief: Log the given message with timestamp
   local record="${@}"
@@ -47,12 +57,12 @@ errexit(){
 } >&2; export -f errexit
 
 ranpick(){
-  # Brief: Pick a word randomly from stdin
+  # Brief: Pick a word randomly from stdin. Fail for empty inputs.
   local input
-  read -a input
+  read -a input || return 1
   local size="${#input[@]}"
   echo "${input[RANDOM%size]}"
-} < <(xargs) 2>/dev/null; export -f ranpick
+} < <(xargs -r) 2>/dev/null; export -f ranpick
 
 key_val(){
   # Brief: Access value for given JSON key from global or key-specific config
@@ -84,7 +94,7 @@ _ipns_link_init(){
     yesno "Sure you wanna reset everything?" || return
     rm -rf "${root_repo}"
   fi
-  mkdir -p "${root_repo}"
+  mkdir -p "${root_repo}"; touch "${lock}"
   
   local editor
   read -ep "Provide a text editor (path/cmd): " editor && command -v "${editor}" &>/dev/null || errexit "No text editor provided"
@@ -126,6 +136,8 @@ _ipns_link_init(){
   # Configure Publisher
   (export IPFS_PATH="${publisher_repo}"
     ipfs init -e --profile server
+    # Disabling AutoRelay as it is not needed. Also this has an added benefit - see pub_addrs function
+    ipfs config --bool Swarm.EnableAutoRelay false
     # Peering with content-providers to increase the swarm
     # Ref: https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list
     ipfs config --json Peering.Peers '[
@@ -157,34 +169,51 @@ _ipns_link_init(){
   mkdir -p "${GNUPGHOME}" "${TMPDIR}" 
   
   # Finish off with stamping current version number in config
-  jq ".version=\"${version}\"|.editor=\"${editor}\"|.Listener.port=null|.trusted_gateways=[]" <<< '{}' > "${config}"
+  jq ".version=\"${version}\"
+    |.editor=\"${editor}\"
+    |.Listener.port=null
+    |.Publisher.port=null
+    |.trusted_gateways=[]" <<< '{}' > "${config}"
 } >&2
 
 p_ipfs(){
   # Brief: Wrapper function for publisher node that includes resuming it and pausing
   # Usage: p_ipfs [<ipfs-cli options and argments>]
-  local pid="$(<"${publisher_pid}")"
-  kill -CONT "${pid}" &>/dev/null
-  timeout 30 ipfs -c "${publisher_repo}" "${@}"; local exit_code="${?}"
-  kill -STOP "${pid}" &>/dev/null
+  flock -s 0 # Lock of publisher_pid announces Publisher is at work
+  local pid; read pid
+  # Try to wake publisher up until successful
+  until kill -CONT "${pid}" && timeout 1 ipfs -c "${publisher_repo}" swarm peers; do
+    kill -0 "${pid}" || break # Makes sure publisher is alive, even if stopped. Otherwise offline mode 
+  done &>/dev/null
+  ipfs -c "${publisher_repo}" "${@}"; local exit_code="${?}" # The actual work
+  flock -u 0 # Drop the lock because work is done
+  flock -n "${publisher_pid}" -c "kill -STOP ${pid}" &>/dev/null # Cant pause Publisher when some other worker is using it
   return "${exit_code}"
-}; export -f p_ipfs
+} <"${publisher_pid}"; export -f p_ipfs
 
 public_route(){
   # Brief: Seek and output public route, if any. Set up peering with relay, if any.
   # Usage: public_route
   log "Seeking public address for Origin-server"
   local local_addrs="$(ipfs -c "${origin_repo}" diag sys | jq -r .net.interface_addresses[])"
-  
+  local origin_ID="$(ipfs -c "${origin_repo}" id -f='<id>')"
+
   pub_addrs(){
     # Brief: Get complete public multiaddress
     ipfs -c "${origin_repo}" id -f="<addrs>" | grep -v '^/p2p/' | grep -vf <(echo "${local_addrs}")
+    # Remark: Due to a bug in go-ipfs, public IP, even if any, is replaced by p2p-circuit, once relay hop is availed
+    # So, if Publisher, with AutoRelay disabled, has a public IP, let's use it
+    local publisher_port="$(p_ipfs config Addresses.Swarm | jq -r .[] | grep -o '/tcp/.*$')"
+    local origin_port="$(ipfs -c "${origin_repo}" config Addresses.Swarm | jq -r .[] | grep -o '/tcp/.*$')"
+    p_ipfs id -f="<addrs>" | grep -v '/p2p-circuit/' | grep -vf <(echo "${local_addrs}") | \
+      grep -o ".*${publisher_port}" | sed "s/[[:digit:]]*$/${origin_port##*/}\/p2p\/${origin_ID}/"
   }; export -f pub_addrs
   
   test_conn(){
     # Brief: Test if given multiaddresses can be connected to. Read multiaddress from stdin.
     local multiaddress
     while read multiaddress;do
+      [[ -n "${multiaddress}" ]] || continue
       p_ipfs swarm disconnect "$(grep -o '/p2p/[[:alnum:]]*$' <<< "${multiaddress}")"
       p_ipfs swarm connect "${multiaddress}" && log "Connection test passed" && return 0
       log "Connection test failed for ${multiaddress}"
@@ -201,7 +230,8 @@ public_route(){
     # Peering with relay exists. So restart needed. Fresh launch clears peering with relay.
       local buffer="$(ipfs -c "${origin_repo}" p2p ls | awk '{print $1,$3}')" # Hold current protocol and target
       ipfs -c "${origin_repo}" shutdown ; log "Relaunching Origin-server"
-      IPFS_PATH="${origin_repo}" launcher --enable-namesys-pubsub && log "Origin-server launched" # Relaunch
+      IPFS_PATH="${origin_repo}" IPFS_PORT="$(key_val Listener.port)" launcher --enable-namesys-pubsub && \
+        log "Origin-server launched" # Relaunch
       xargs -rn2 ipfs -c "${origin_repo}" p2p listen <<< "${buffer}" # Re-establish listeners
     else
       sleep 1
@@ -219,6 +249,7 @@ publish_manifest(){
   # Usage: publish_manifest <key name>
   local name="${1}" routes
   routes="$(public_route)" || return 1
+  local keyID="$(p_ipfs key list -l | grep -wm1 "${name}" | awk '{print $1}')"
   local ID="$(ipfs -c "${origin_repo}" id -f='<id>')"
   local routes_json="$(echo -n "${routes}" | jq --raw-input --slurp 'split("\n")')"
   local ciphertext="$(jq "del(.local)|.multiaddress.route=${routes_json}|.multiaddress.ID=\"${ID}\"" "${staging}/${name}" | \
@@ -226,8 +257,8 @@ publish_manifest(){
   ipfs -c "${origin_repo}" multibase encode -b base64
   )"
   local trusted_gw="$(key_val trusted_gateways[])"
-  local random_gw="$(awk '{print $1}' "${gw_list}" | ranpick)"
-  local official_gw="$(grep -wim1 official "${gw_list}" | awk '{print $1}')"
+  local random_gw="$(awk '{print $1}' "${gw_list}" | ranpick)"/ipns/"${keyID}"/
+  local official_gw="$(grep -wim1 official "${gw_list}" | awk '{print $1}')"/ipns/"${keyID}"/
   local post="
 <meta http-equiv=\"refresh\" content=\"0; url=${random_gw}\">
 <title>Redirecting...</title>
@@ -243,14 +274,19 @@ ${trusted_gw}
 
 _ipns_link_quit(){
   # Brief: Shutdown everything
-  p_ipfs shutdown
+  flock -n 0 && errexit "Nothing to shutdown" 
+  log "Quit request received"
   local name
   for name in $(ls "${staging}/"); do
     _ipns_link_hide "${name}"
   done
+  gpgconf --kill gpg-agent
   ipfs -c "${origin_repo}" shutdown
-  rm -f "${lock}"
-}
+  local pid; read pid; kill_proc_tree "${pid}"
+  kill_proc_tree "$(<"${publisher_pid}")"
+  : > "${publisher_pid}"; : > "${lock}"
+  echo "Shutdown complete"
+} < "${lock}" >&2
 
 _ipns_link_daemon(){
   # Brief: Launch IPFS daemons in background
@@ -279,7 +315,7 @@ _ipns_link_daemon(){
   } 3>&1 2>/dev/null; export -f launcher
   
   # Launch Publisher
-  IPFS_PATH="${publisher_repo}" launcher --enable-namesys-pubsub > "${publisher_pid}" \
+  IPFS_PATH="${publisher_repo}" IPFS_PORT="$(key_val Publisher.port)" launcher --enable-namesys-pubsub > "${publisher_pid}" \
     || errexit "Failed to launch Publisher"
   p_ipfs swarm peers &>/dev/null && log "Launched Publisher" # Initial pausing
   
@@ -299,8 +335,9 @@ _ipns_link_daemon(){
     fi
     read -t 30 key_name && publish_manifest "${key_name}"
   done < <(inotifywait -m -q -e close_write --format '%f' "${staging}")
+  
+  # In case the above loop exits without calling _ipns_link_quit
   echo > "${staging}/.ipns" # Forces inotifywait to close as it no more has any pipe to write to
-  gpgconf --kill gpg-agent
   log "Quiting"
 } &>/dev/null 10>"${lock}"
 
@@ -524,7 +561,7 @@ report_updates
   [[ "${subcmd}" == init ]] || [[ "${version}" == "$(key_val version)" ]] || errexit "Version mismatch. Do: ipns-link init"
   if [[ "${subcmd}" == daemon ]]; then
     flock -n "${lock}" -c : || errexit "Another instance running"
-    _ipns_link_daemon &
+    _ipns_link_daemon & echo $! | tee "${lock}"
     echo "Tip: To monitor progress use: ipns-link log"
   else
     shift # Make the next CLI-arg after subcmd $1
